### ISSUE TITLE
What to provide as --init_file?

### ISSUE THREAD

**Issue by privefl** [AI-sandbox/neural-admixture#7]
Sorry, but I do not understand what to provide as `--init_file`.
Can you explain to me please?

**Comment by AlbertDominguez** [comment]
On common runs, the `--init_file` argument is basically used to store the PCA object used in the initialization step, in order to save compute time in case the program is run several times.

On "pre-trained" runs, this argument is used to specify the path of the `.P` file containing the frequency matrix _F_/_P_, as generated by ADMIXTURE.
